# Generated by Django 5.1.1 on 2024-09-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posteo',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='posteo_id',
            new_name='post_id',
        ),
    ]
