# Generated by Django 5.1.1 on 2024-09-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_posteo_post_rename_posteo_id_usuario_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
