# Generated by Django 5.1.1 on 2024-09-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
