# Generated by Django 5.1.1 on 2024-09-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.temapost'),
        ),
    ]
